# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a06ef8b153a16b3caf059a124eb981407331cd7a1bd5069f8e7cacbb2193d770b93fc95004e84a0f819f37954918e07db8919a0786336064fac9bb5690fb9271

test:
  secret_key_base: 7a5ec94f1c6895319cdd909400add7ef77465dc271bcff3a36adec9c317a09dac56542ffd48d62f369cd82d65a904ccbdfff3040e6a9414cf27563b871441f39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
